### ISSUE TITLE
FPGA Imaging Library Error

### ISSUE THREAD

**Issue by Ekrem54** [dtysky/Image-processing-on-FPGA#2]
I tried to implement a test for the mean filter. When  I try to run the create.py file I got these errors. I inserted an image to the ImageForTest file same as your test image "http://fil.dtysky.moe/en/wiki/mean-filter-en.html".I attached the conf.json file also. I am using Python 3.9.6 and PIL installed.
Any help would be appreciated.

![Image 2021-07-13 at 15 14 57](https://user-images.githubusercontent.com/84246903/125450664-4bd483bf-0fbc-4d38-9226-5b145066713f.jpeg)

Written in conf.json   file:

{
	"conf" : [
		{"window_width" : 3},
		{"window_width" : 5}
	]
}

**Comment by dtysky** [comment]
HI, I wrote this project long time ago so it only supports python2.x
